version: '3.8'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - registry:/var/lib/registry
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.8
  
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    restart: always
    volumes:
      - ./regui:/etc/apache2/server.crt
      - ./regui:/etc/apache2/server.key
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.9

volumes:
  registry:
    name: registry

networks:
  dotnetwork:
    name: dotnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1