version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token <your-token>
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.4

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.5

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.6

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.7
  
volumes:
  portainer:
    name: portainer
  jenkins:
    name: jenkins

networks:
  dotnetwork:
    name: dotnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1