version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: <change-with-your-password>
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.2

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.3

volumes:
  postgres:
    name: postgres

networks:
  dotnetwork:
    name: dotnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1